version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_DB: management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rr
      PGDATA: /data/postgres
    volumes:
      - ./configuration/postgres-event-service:/data/postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    command: -p 5432
  backend:
    container_name: backend
    image: reluckyyy/empbackend
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      'spring.datasource.url': jdbc:postgresql://relucky-server.fibo.cloud:30297/management