spring:
  datasource:
    username: postgres
    password: rr
    url: jdbc:postgresql://localhost:5432/management
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  mvc:
    mapping: "/**"
    allowed:
      credentials: true
      origin-patterns: "http://localhost:4200/"
      headers: "*"
      methods: "*"
server:
  port: 8888
